language: clojure
script:
  - jdk_switcher use openjdk6
  - lein with-profile dev:dev,1.7:dev,1.8:dev,1.9 test
  - lein with-profile 1.7:1.8 doo node once
  - jdk_switcher use openjdk7
  - lein with-profile dev:dev,1.7:dev,1.8:dev,1.9 test
  - lein with-profile 1.7:1.8 doo node once
  - jdk_switcher use openjdk8
  - lein with-profile dev:dev,1.7:dev,1.8:dev,1.9 test
  - lein with-profile 1.7:1.8:1.9 doo node once
